completed #6 GET /api/reviews/:review_id/comments
tyrese-s/be-game-project pull request #5
Opened 2023-02-22 09:57 UTC by tyrese-s

2023-02-22 10:14 UTC, HannahBurks requested changes
Hey Tyrese, very nice work! Just one extra test to add in this case, once added please send another PR 😄

2023-02-22 10:14 UTC, HannahBurks commented on __tests__/app.test.js
> +    })
We also want to add a test here (200) - that if the ID exists but there is no comments that it returns an empty array.

2023-02-22 11:11 UTC, jimstev2447 commented on __tests__/app.test.js
> +    })
you've got a test for invalid id but are missing one for valid but non existent e.g /api/reviews/1000/comments
I would recommend add ing it in here

2023-02-22 11:11 UTC, jimstev2447 commented on __tests__/app.test.js
> +    // describe('POST/api/reviews/:review_id/comments', () => {
try to avoid leaving in commented out code it can make merge conflicts more likely and you dont know if its needed yet :)

2023-02-23 12:39 UTC, cjplatten commented
When adding files to a commit don't just add every file by default, instead only add the files that are relevent to the commit. There are changes included in this commit that are for a different ticket entirely, this makes it harder to review and could cause you problems if you ever needed to revert to a previous commit. 

Otherwise, this is ok to merge.

2023-02-23 13:05 UTC, merged